/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banco;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import java.awt.Color;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author harum
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    //inicializar clases
    
     ListaSE<Solicitud> solicitudes = new ListaSE<>();
     ListaSE<Cuenta> cuentas = new ListaSE<>();
     Banco b=new Banco(solicitudes,cuentas);
     int posicion = -1;
     
    public Inicio() {
        initComponents();
        InitStyles();
        
    }
    private void InitStyles(){
        inicio.putClientProperty( "FlatLaf.styleClass", "h1" );
        inicio.setForeground(Color.white);
        texto1.putClientProperty( "FlatLaf.styleClass", "h4" );
        texto1.setForeground(Color.white);
        texto2.putClientProperty( "FlatLaf.styleClass", "h4" );
        texto2.setForeground(Color.white);
        texto3.putClientProperty( "FlatLaf.styleClass", "h4" );
        texto3.setForeground(Color.white);
        texto4.putClientProperty( "FlatLaf.styleClass", "h4" );
        texto4.setForeground(Color.white);
        texto5.putClientProperty( "FlatLaf.styleClass", "h4" );
        texto5.setForeground(Color.white);
        texto6.putClientProperty( "FlatLaf.styleClass", "h4" );
        texto6.setForeground(Color.white);
        texto7.putClientProperty( "FlatLaf.styleClass", "h4" );
        texto7.setForeground(Color.white);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        inicio = new javax.swing.JLabel();
        cerrarCuenta = new javax.swing.JButton();
        texto1 = new javax.swing.JLabel();
        atenderSolicitudes = new javax.swing.JButton();
        texto2 = new javax.swing.JLabel();
        mostrarCuentas = new javax.swing.JButton();
        texto3 = new javax.swing.JLabel();
        millonarios = new javax.swing.JButton();
        texto4 = new javax.swing.JLabel();
        verificarCuenta = new javax.swing.JButton();
        texto5 = new javax.swing.JLabel();
        crearCuenta = new javax.swing.JButton();
        texto6 = new javax.swing.JLabel();
        crearCuenta2 = new javax.swing.JButton();
        crearSolicitud = new javax.swing.JButton();
        texto7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 450));

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio.setText("Inicio");
        background.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 130, 46));

        cerrarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b2.jpg"))); // NOI18N
        cerrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarCuentaActionPerformed(evt);
            }
        });
        background.add(cerrarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 130, 125));

        texto1.setText("Cerrar cuenta");
        background.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 81, -1));

        atenderSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b4.jpeg"))); // NOI18N
        atenderSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderSolicitudesActionPerformed(evt);
            }
        });
        background.add(atenderSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 130, 125));

        texto2.setText("Dar de baja a millonarios");
        background.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 150, -1));

        mostrarCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b7.jpeg"))); // NOI18N
        mostrarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCuentasActionPerformed(evt);
            }
        });
        background.add(mostrarCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 125));

        texto3.setText("Mostrar cuentas");
        background.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 110, 20));

        millonarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b5.jpeg"))); // NOI18N
        millonarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                millonariosActionPerformed(evt);
            }
        });
        background.add(millonarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 130, 125));

        texto4.setText("Verificar cuenta");
        background.add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 90, -1));

        verificarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b3.jpeg"))); // NOI18N
        verificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarCuentaActionPerformed(evt);
            }
        });
        background.add(verificarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 130, 125));

        texto5.setText("Atender todas las solicitudes");
        background.add(texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 170, -1));

        crearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.jpg"))); // NOI18N
        crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaActionPerformed(evt);
            }
        });
        background.add(crearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, 125));

        texto6.setText("Crear cuenta");
        background.add(texto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 81, -1));

        crearCuenta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.jpg"))); // NOI18N
        crearCuenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuenta2ActionPerformed(evt);
            }
        });
        background.add(crearCuenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, 125));

        crearSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b6.jpeg"))); // NOI18N
        crearSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSolicitudActionPerformed(evt);
            }
        });
        background.add(crearSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 125));

        texto7.setText("Crear solicitud de depósito");
        background.add(texto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCuentasActionPerformed
        if(cuentas==null){
            JOptionPane.showMessageDialog(null,"No hay cuentas para mostrar");
        }else{
            String cuentasConc="";
            for (int i=0;i<cuentas.tamanio();i++){
                String nIdentidad = Integer.toString(cuentas.Obtener(i).getCuenta().getN_identidad());
                String saldo = Double.toString(cuentas.Obtener(i).getCuenta().getSaldo_actual());
                cuentasConc +="No. de Identidad: " + nIdentidad + ", Saldo: " + saldo + "\n";
                
            }
            JOptionPane.showMessageDialog(null,"A continuación se muestran las cuentas actualizadas:\n"+ cuentasConc);

        }
    }//GEN-LAST:event_mostrarCuentasActionPerformed

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaActionPerformed
      JTextField t1 = new JTextField(5);
      JTextField t2 = new JTextField(5);
      
      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("No. de Identidad:"));
      myPanel.add(t1);
      myPanel.add(Box.createHorizontalStrut(15)); // espaciador
      myPanel.add(new JLabel("Saldo:"));
      myPanel.add(t2);
      

      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Ingrese los datos de su cuenta: ", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
          String nIdentidad = t1.getText();
      String saldo = t2.getText();
          posicion++;
          cuentas.Agregar(new NodoSE<>(new Cuenta(Integer.parseInt(nIdentidad),Float.parseFloat(saldo), posicion)));
          JOptionPane.showMessageDialog(null,"Cuenta creada con los datos:\n No. de Identidad:  "+ nIdentidad +", Saldo: " + saldo);
      }
        
    }//GEN-LAST:event_crearCuentaActionPerformed

    private void crearCuenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuenta2ActionPerformed
          
   
    }//GEN-LAST:event_crearCuenta2ActionPerformed

    private void crearSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSolicitudActionPerformed
      JTextField t1 = new JTextField(5);
      JTextField t2 = new JTextField(5);
      JTextField t3 = new JTextField(15);
      
      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("No. de Identidad:"));
      myPanel.add(t1);
      myPanel.add(Box.createHorizontalStrut(15)); // espaciador
      myPanel.add(new JLabel("Cantidad a depositar:"));
      myPanel.add(t2);
      myPanel.add(new JLabel("Nombre del beneficiario:"));
      myPanel.add(t3);
     

      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Ingrese los datos de la cuenta a depositar: ", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
          String nIdentidad = t1.getText();
          String cant_depositar = t2.getText();
          String nombre = t3.getText();
          
          solicitudes.Agregar(new NodoSE<>(new Solicitud(Integer.parseInt(nIdentidad),Float.parseFloat(cant_depositar), nombre)));
          /*if(b.VerificarCuenta()>cuentas.tamanio()){
              
          }*/
          JOptionPane.showMessageDialog(null,"Solicitud creada con los datos:\n No. de Identidad:  "+ nIdentidad +", Cantidad: " + cant_depositar + ", Nombre: "+nombre+"\n La solicitud se encuentra pendiente");
      }
    }//GEN-LAST:event_crearSolicitudActionPerformed

    private void cerrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarCuentaActionPerformed
      JTextField t1 = new JTextField(5);
      
      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("No. de Identidad:"));
      myPanel.add(t1);

      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Cuenta que desea eliminar: ", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
          String nIdentidad = t1.getText();
     
        boolean existe = false;
        for(int i=0;i<cuentas.tamanio();i++){
            if(cuentas.Obtener(i).getCuenta().getN_identidad()==Integer.parseInt(nIdentidad)){
                cuentas.Eliminar(cuentas.Obtener(i));
                existe = true;
            }
        }
              
          if(existe){
             JOptionPane.showMessageDialog(null,"La cuenta con el no. de Identidad:  "+ nIdentidad +" fue eliminada");

          }else{
               JOptionPane.showMessageDialog(null,"La cuenta con el no. de Identidad:  "+ nIdentidad +" no existe");
          }
         
      }
    }//GEN-LAST:event_cerrarCuentaActionPerformed

    private void verificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarCuentaActionPerformed

            if(solicitudes.tamanio()>0){
                int tamanio_ini=cuentas.tamanio();
                b.VerificarCuenta(solicitudes.Obtener(0));
                if(tamanio_ini==cuentas.tamanio()){
                    JOptionPane.showMessageDialog(null,"La cuenta de la primera solicitud ha sido verificada y su información actualizada");
                }
                else{
                    JOptionPane.showMessageDialog(null,"La cuenta de la primera solicitud ha sido verificada, se creó una nueva cuenta");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Actualmente no existen solicitudes, intente crear una nueva solicitud");
            }
            
    }//GEN-LAST:event_verificarCuentaActionPerformed

    private void atenderSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderSolicitudesActionPerformed
        b.AtenderTodasLasSolicitudes();
        
        JOptionPane.showMessageDialog(null,"Todas las solicitudes han sido atendidas, para mostrar las cuentas actualizadas de click en el botón 'Mostrar cuentas'");
        
    }//GEN-LAST:event_atenderSolicitudesActionPerformed

    private void millonariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_millonariosActionPerformed
        b.DarBajaAMillonarios();
        JOptionPane.showMessageDialog(null,"Todos los millonarios fueron dados de baja, para mostrar las cuentas actualizadas de click en el botón 'Mostrar cuentas'");
        
    }//GEN-LAST:event_millonariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightFlatIJTheme.setup();
  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atenderSolicitudes;
    private javax.swing.JPanel background;
    private javax.swing.JButton cerrarCuenta;
    private javax.swing.JButton crearCuenta;
    private javax.swing.JButton crearCuenta2;
    private javax.swing.JButton crearSolicitud;
    private javax.swing.JLabel inicio;
    private javax.swing.JButton millonarios;
    private javax.swing.JButton mostrarCuentas;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JButton verificarCuenta;
    // End of variables declaration//GEN-END:variables
}
